#include "colour_repr.h"

const std::vector<std::string> _cpf_colour_tokens = {
	/*default*/
	"!",

	/*dim text colour no background*/
	"r", "g", "b", "y", "m", "c", "w", "0",

	/*bright text colour no background*/
	"r!", "g!", "b!", "y!", "m!", "c!", "w!", "0!",

	/*dim text and background colour*/
	"rr", "rb", "rg", "ry", "rm", "rc", "rw", "r0",/*red*/
	"gg", "gb", "gr", "gy", "gm", "gc", "gw", "g0",/*green*/
	"bb", "br", "bg", "by", "bm", "bc", "bw", "b0",/*blue*/
	"yy", "yb", "yg", "yr", "ym", "yc", "yw", "y0",/*yellow*/
	"mm", "mr", "mg", "my", "mb", "mc", "mw", "m0",/*magenta*/
	"cc", "cr", "cg", "cy", "cm", "cb", "cw", "c0",/*cyan*/
	"ww", "wr", "wg", "wy", "wm", "wc", "wb", "w0",/*white*/
	"00", "0r", "0g", "0y", "0m", "0c", "0b", "0w",/*black*/

	/*bright text colour and dim background colour*/
	"r!r", "r!b", "r!g", "r!y", "r!m", "r!c", "r!w", "r!0", 	/*red*/
	"g!g", "g!b", "g!r", "g!y", "g!m", "g!c", "g!w", "g!0",	/*green*/
	"b!b", "b!r", "b!g", "b!y", "b!m", "b!c", "b!w", "b!0",	/*blue*/
	"y!y", "y!b", "y!g", "y!r", "y!m", "y!c", "y!w", "y!0",	/*yellow*/
	"m!m", "m!r", "m!g", "m!y", "m!b", "m!c", "m!w", "m!0",	/*magenta*/
	"c!c", "c!r", "c!g", "c!y", "c!m", "c!b", "c!w", "c!0",	/*cyan*/
	"w!w", "w!r", "w!g", "w!y", "w!m", "w!c", "w!b", "w!0",	/*white*/
	"0!0", "0!r", "0!g", "0!y", "0!m", "0!c", "0!b", "0!w",/*black*/

	/*dim text colour and bright background colour*/
	"rr!", "rb!", "rg!", "ry!", "rm!", "rc!", "rw!", "r0!",/*red*/
	"gg!", "gb!", "gr!", "gy!", "gm!", "gc!", "gw!", "g0!",/*green*/
	"bb!", "br!", "bg!", "by!", "bm!", "bc!", "bw!", "b0!",/*blue*/
	"yy!", "yb!", "yg!", "yr!", "ym!", "yc!", "yw!", "y0!",	/*yellow*/
	"mm!", "mr!", "mg!", "my!", "mb!", "mc!", "mw!", "m0!",	/*magenta*/
	"cc!", "cr!", "cg!", "cy!", "cm!", "cb!", "cw!", "c0!",	/*cyan*/
	"ww!", "wr!", "wg!", "wy!", "wm!", "wc!", "wb!", "w0!",	/*white*/
	"00!", "0r!", "0g!", "0y!", "0m!", "0c!", "0b!", "0w!",/*black*/

	/*bright text and background colour*/
	"r!r!", "r!b!", "r!g!", "r!y!", "r!m!", "r!c!", "r!w!", "r!0!",/*red*/
	"g!g!", "g!b!", "g!r!", "g!y!", "g!m!", "g!c!", "g!w!", "g!0!",/*green*/
	"b!b!", "b!r!", "b!g!", "b!y!", "b!m!", "b!c!", "b!w!", "b!0!",/*blue*/
	"y!y!", "y!b!", "y!g!", "y!r!", "y!m!", "y!c!", "y!w!", "y!0!",/*yellow*/
	"m!m!", "m!r!", "m!g!", "m!y!", "m!b!", "m!c!", "m!w!", "m!0!",/*magenta*/
	"c!c!", "c!r!", "c!g!", "c!y!", "c!m!", "c!b!", "c!w!", "c!0!",/*cyan*/
	"w!w!", "w!r!", "w!g!", "w!y!", "w!m!", "w!c!", "w!b!", "w!0!",/*white*/
	"0!0!", "0!r!", "0!g!", "0!y!", "0!m!", "0!c!", "0!b!", "0!w!",/*black*/
};

#ifdef _WIN32

const std::map<const std::string, colour_t> _cpf_colour_token_vals{
	/*default*/
	{ "!", [&]()->colour_t
	{
		CONSOLE_SCREEN_BUFFER_INFO csbi;
		GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi);
		auto a = csbi.wAttributes;
		return static_cast<colour_t>(a % 16);
	}()
	},

	/*black*/

	{ "0", (FOREGROUND_RED) },
	{ "0!", (FOREGROUND_RED | FOREGROUND_INTENSITY) },

	{ "0r", (FOREGROUND_RED | BACKGROUND_RED) },
	{ "0b", (FOREGROUND_RED | BACKGROUND_BLUE) },
	{ "0g", (FOREGROUND_RED | BACKGROUND_GREEN) },
	{ "0y", (FOREGROUND_RED | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "0m", (FOREGROUND_RED | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "0c", (FOREGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "0w", (FOREGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "0!r", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "0!b", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "0!g", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "0!y", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "0!m", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "0!c", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "0!w", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "0r!", ((FOREGROUND_RED) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "0b!", ((FOREGROUND_RED) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0g!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0y!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0m!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0c!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0w!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "0!r!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "0!b!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0!g!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0!y!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0!m!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0!c!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0!w!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*red*/
	{ "r", (FOREGROUND_RED) },
	{ "r!", (FOREGROUND_RED | FOREGROUND_INTENSITY) },

	{ "rr", (FOREGROUND_RED | BACKGROUND_RED) },
	{ "rb", (FOREGROUND_RED | BACKGROUND_BLUE) },
	{ "rg", (FOREGROUND_RED | BACKGROUND_GREEN) },
	{ "ry", (FOREGROUND_RED | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "rm", (FOREGROUND_RED | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "rc", (FOREGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "rw", (FOREGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "r!r", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "r!b", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "r!g", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "r!y", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "r!m", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "r!c", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "r!w", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "rr!", ((FOREGROUND_RED) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "rb!", ((FOREGROUND_RED) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "rg!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "ry!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "rm!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "rc!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "rw!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "r!r!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "r!b!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "r!g!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "r!y!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "r!m!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "r!c!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "r!w!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*green*/

	{ "g", (FOREGROUND_GREEN) },
	{ "g!", (FOREGROUND_GREEN | FOREGROUND_INTENSITY) },

	{ "gr", (FOREGROUND_GREEN | BACKGROUND_RED) },
	{ "gb", (FOREGROUND_GREEN | BACKGROUND_BLUE) },
	{ "gg", (FOREGROUND_GREEN | BACKGROUND_GREEN) },
	{ "gy", (FOREGROUND_GREEN | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "gm", (FOREGROUND_GREEN | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "gc", (FOREGROUND_GREEN | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "gw", (FOREGROUND_GREEN | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "g!r", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "g!b", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "g!g", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "g!y", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "g!m", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "g!c", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "g!w", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "gr!", ((FOREGROUND_GREEN) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "gb!", ((FOREGROUND_GREEN) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "gg!", (FOREGROUND_GREEN | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "gy!", (FOREGROUND_GREEN | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "gm!", (FOREGROUND_GREEN | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "gc!", (FOREGROUND_GREEN | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "gw!", (FOREGROUND_GREEN | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "g!r!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "g!b!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "g!g!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "g!y!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "g!m!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "g!c!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "g!w!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*blue*/

	{ "b", (FOREGROUND_BLUE) },
	{ "b!", (FOREGROUND_BLUE | FOREGROUND_INTENSITY) },

	{ "br", (FOREGROUND_BLUE | BACKGROUND_RED) },
	{ "bb", (FOREGROUND_BLUE | BACKGROUND_BLUE) },
	{ "bg", (FOREGROUND_BLUE | BACKGROUND_GREEN) },
	{ "by", (FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "bm", (FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "bc", (FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "bw", (FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "b!r", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "b!b", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "b!g", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "b!y", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "b!m", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "b!c", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "b!w", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "br!", ((FOREGROUND_BLUE) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "bb!", ((FOREGROUND_BLUE) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "bg!", (FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "by!", (FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "bm!", (FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "bc!", (FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "bw!", (FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "b!r!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "b!b!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "b!g!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "b!y!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "b!m!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "b!c!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "b!w!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*yellow*/

	{ "y", (FOREGROUND_RED | FOREGROUND_GREEN) },
	{ "y!", ((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) },

	{ "yr", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_RED) },
	{ "yb", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_BLUE) },
	{ "yg", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_GREEN) },
	{ "yy", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "ym", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "yc", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "yw", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "y!r", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "y!b", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "y!g", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "y!y", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "y!m", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "y!c", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "y!w", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "yr!", (((FOREGROUND_RED | FOREGROUND_GREEN)) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "yb!", (((FOREGROUND_RED | FOREGROUND_GREEN)) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "yg!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "yy!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "ym!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "yc!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "yw!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "y!r!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "y!b!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "y!g!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "y!y!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "y!m!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "y!c!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "y!w!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*magenta*/

	{ "m", (FOREGROUND_RED | FOREGROUND_BLUE) },
	{ "m!", (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) },

	{ "mr", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_RED) },
	{ "mb", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_BLUE) },
	{ "mg", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_GREEN) },
	{ "my", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "mm", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "mc", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "mw", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "m!r", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "m!b", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "m!g", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "m!y", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "m!m", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "m!c", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "m!w", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "mr!", ((FOREGROUND_RED | FOREGROUND_BLUE) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
ET (CMAKE_CXX_FLAGS                "-Wall")
	{ "mg!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "my!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "mm!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "mc!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "mw!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "m!r!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "m!b!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "m!g!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "m!y!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "m!m!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "m!c!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "m!w!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*cyan*/

	{ "c", (FOREGROUND_GREEN | FOREGROUND_BLUE) },
	{ "c!", (FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) },

	{ "cr", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_RED) },
	{ "cb", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_BLUE) },
	{ "cg", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_GREEN) },
	{ "cy", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "cm", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "cc", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "cw", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "c!r", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "c!b", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "c!g", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "c!y", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "c!m", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "c!c", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "c!w", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "cr!", ((FOREGROUND_GREEN | FOREGROUND_BLUE) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "cb!", ((FOREGROUND_GREEN | FOREGROUND_BLUE) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "cg!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "cy!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "cm!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "cc!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "cw!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "c!r!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "c!b!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "c!g!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "c!y!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "c!m!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "c!c!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "c!w!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	/*white*/

	{ "w", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)) },
	{ "w!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) },

	{ "wr", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "wb", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "wg", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "wy", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "wm", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "wc", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "ww", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "w!r", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "w!b", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "w!g", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "w!y", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "w!m", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "w!c", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "w!w", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "wr!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "wb!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "wg!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "wy!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "wm!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "wc!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "ww!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "w!r!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "w!b!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "w!g!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "w!y!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "w!m!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "w!c!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "w!w!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) }

};

#else //_WIN32
//http://www.linuxhomenetworking.com/forums/showthread.php/1095-Linux-console-Colors-And-Other-Trick-s
//http://stackoverflow.com/questions/3506504/c-code-changes-terminal-text-color-how-to-restore-defaults-linux
//http://linuxgazette.net/issue65/padala.html

extern const std::map<const std::string, colour_t> _cpf_colour_token_vals{
	{	"r",	"\x1B[31m" },
    {	"g",	"\x1B[32m" },
    {	"b",	"\x1B[34m" },
    {	"r!",	"\x1B[31m" },
    {	"g!",	"\x1B[32m" },
    {	"b!",	"\x1B[34m" },

    /*default*/
	{ "!", "\x1B[0m"}
};
	/*black*/

	/*{ "0",  },
	{ "0!",  },

	{ "0r",  },
	{ "0b",  },
	{ "0g",  },
	{ "0y",  },
	{ "0m",  },
	{ "0c",  },
	{ "0w",  },*/
    /*
	{ "0!r", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "0!b", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "0!g", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "0!y", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "0!m", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "0!c", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "0!w", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "0r!", ((FOREGROUND_RED) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "0b!", ((FOREGROUND_RED) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0g!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0y!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0m!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0c!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0w!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "0!r!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "0!b!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0!g!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0!y!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "0!m!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0!c!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "0!w!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//red
	{ "r", (FOREGROUND_RED) },
	{ "r!", (FOREGROUND_RED | FOREGROUND_INTENSITY) },

	{ "rr", (FOREGROUND_RED | BACKGROUND_RED) },
	{ "rb", (FOREGROUND_RED | BACKGROUND_BLUE) },
	{ "rg", (FOREGROUND_RED | BACKGROUND_GREEN) },
	{ "ry", (FOREGROUND_RED | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "rm", (FOREGROUND_RED | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "rc", (FOREGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "rw", (FOREGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "r!r", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "r!b", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "r!g", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "r!y", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "r!m", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "r!c", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "r!w", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "rr!", ((FOREGROUND_RED) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "rb!", ((FOREGROUND_RED) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "rg!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "ry!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "rm!", (FOREGROUND_RED | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "rc!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "rw!", (FOREGROUND_RED | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "r!r!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "r!b!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "r!g!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "r!y!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "r!m!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "r!c!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "r!w!", ((FOREGROUND_RED | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//green

	{ "g", (FOREGROUND_GREEN) },
	{ "g!", (FOREGROUND_GREEN | FOREGROUND_INTENSITY) },

	{ "gr", (FOREGROUND_GREEN | BACKGROUND_RED) },
	{ "gb", (FOREGROUND_GREEN | BACKGROUND_BLUE) },
	{ "gg", (FOREGROUND_GREEN | BACKGROUND_GREEN) },
	{ "gy", (FOREGROUND_GREEN | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "gm", (FOREGROUND_GREEN | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "gc", (FOREGROUND_GREEN | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "gw", (FOREGROUND_GREEN | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "g!r", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "g!b", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "g!g", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "g!y", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "g!m", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "g!c", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "g!w", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "gr!", ((FOREGROUND_GREEN) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "gb!", ((FOREGROUND_GREEN) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "gg!", (FOREGROUND_GREEN | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "gy!", (FOREGROUND_GREEN | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "gm!", (FOREGROUND_GREEN | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "gc!", (FOREGROUND_GREEN | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "gw!", (FOREGROUND_GREEN | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "g!r!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "g!b!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "g!g!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "g!y!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "g!m!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "g!c!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "g!w!", ((FOREGROUND_GREEN | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//blue

	{ "b", (FOREGROUND_BLUE) },
	{ "b!", (FOREGROUND_BLUE | FOREGROUND_INTENSITY) },

	{ "br", (FOREGROUND_BLUE | BACKGROUND_RED) },
	{ "bb", (FOREGROUND_BLUE | BACKGROUND_BLUE) },
	{ "bg", (FOREGROUND_BLUE | BACKGROUND_GREEN) },
	{ "by", (FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "bm", (FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "bc", (FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "bw", (FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "b!r", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "b!b", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "b!g", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "b!y", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "b!m", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "b!c", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "b!w", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "br!", ((FOREGROUND_BLUE) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "bb!", ((FOREGROUND_BLUE) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "bg!", (FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "by!", (FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "bm!", (FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "bc!", (FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "bw!", (FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "b!r!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "b!b!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "b!g!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "b!y!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "b!m!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "b!c!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "b!w!", ((FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//yellow

	{ "y", (FOREGROUND_RED | FOREGROUND_GREEN) },
	{ "y!", ((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) },

	{ "yr", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_RED) },
	{ "yb", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_BLUE) },
	{ "yg", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_GREEN) },
	{ "yy", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "ym", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "yc", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "yw", ((FOREGROUND_RED | FOREGROUND_GREEN) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "y!r", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "y!b", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "y!g", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "y!y", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "y!m", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "y!c", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "y!w", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "yr!", (((FOREGROUND_RED | FOREGROUND_GREEN)) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "yb!", (((FOREGROUND_RED | FOREGROUND_GREEN)) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "yg!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "yy!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "ym!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "yc!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "yw!", ((FOREGROUND_RED | FOREGROUND_GREEN) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "y!r!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "y!b!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "y!g!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "y!y!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "y!m!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "y!c!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "y!w!", (((FOREGROUND_RED | FOREGROUND_GREEN) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//magenta

	{ "m", (FOREGROUND_RED | FOREGROUND_BLUE) },
	{ "m!", (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) },

	{ "mr", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_RED) },
	{ "mb", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_BLUE) },
	{ "mg", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_GREEN) },
	{ "my", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "mm", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "mc", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "mw", (FOREGROUND_RED | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "m!r", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "m!b", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "m!g", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "m!y", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "m!m", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "m!c", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "m!w", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "mr!", ((FOREGROUND_RED | FOREGROUND_BLUE) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "mb!", ((FOREGROUND_RED | FOREGROUND_BLUE) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "mg!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "my!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "mm!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "mc!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "mw!", (FOREGROUND_RED | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "m!r!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "m!b!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "m!g!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "m!y!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "m!m!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "m!c!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "m!w!", ((FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//cyan

	{ "c", (FOREGROUND_GREEN | FOREGROUND_BLUE) },
	{ "c!", (FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) },

	{ "cr", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_RED) },
	{ "cb", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_BLUE) },
	{ "cg", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_GREEN) },
	{ "cy", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "cm", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "cc", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "cw", (FOREGROUND_GREEN | FOREGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "c!r", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "c!b", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "c!g", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "c!y", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "c!m", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "c!c", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "c!w", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "cr!", ((FOREGROUND_GREEN | FOREGROUND_BLUE) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "cb!", ((FOREGROUND_GREEN | FOREGROUND_BLUE) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "cg!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "cy!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "cm!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "cc!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "cw!", (FOREGROUND_GREEN | FOREGROUND_BLUE | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "c!r!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "c!b!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "c!g!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "c!y!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "c!m!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "c!c!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "c!w!", ((FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	//white

	{ "w", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)) },
	{ "w!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) },

	{ "wr", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "wb", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "wg", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "wy", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "wm", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "wc", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "ww", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "w!r", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_RED) },
	{ "w!b", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_BLUE) },
	{ "w!g", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN) },
	{ "w!y", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_GREEN) },
	{ "w!m", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_RED | BACKGROUND_BLUE) },
	{ "w!c", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE) },
	{ "w!w", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED) },

	{ "wr!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)) | (BACKGROUND_RED | BACKGROUND_INTENSITY)) },
	{ "wb!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "wg!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "wy!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "wm!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "wc!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "ww!", ((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) },

	{ "w!r!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_INTENSITY | BACKGROUND_RED)) },
	{ "w!b!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "w!g!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "w!y!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY)) },
	{ "w!m!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "w!c!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY)) },
	{ "w!w!", (((FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY) | FOREGROUND_INTENSITY) | (BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY)) }
*/
//};

#endif //_WIN32
